spring:
 application:
  name: casinorep
 datasource:
  url: jdbc:h2:mem:mydb
  username: sa
  password: password
  driverClassName: org.h2.Driver
 jpa:
  database-platform: org.hibernate.dialect.H2Dialect
 h2:
  console:
   enabled: true
 servlet:
  multipart:
   file-size-threshold: 2KB
   max-file-size: 10MB
   max-request-size: 10MB
   
logging:
 level:
  com.reporter.pdf.casinorep: TRACE
  
rsc_path: /home/asus13/Documents/projects/casinorep/resources
base_images:
 path: /assets/img/basic/
 logo_aseco: LogoAsecco.jpg
 logo_limpo: Logolimposervices.jpg
 files_base:
  - ProductoCleaner_1.jpg
  - ProductoCleaner_2.jpg
documental_images: /documental/images/
documental_pdfs: /documental/pdfs/