spring:
 application:
  name: casinorep
  
logging:
 level:
  com.reporter.pdf.casinorep: TRACE
  
rsc_path: /home/asus13/Documents/projects/casinorep/resources
base_images:
 path: /assets/img/basic/
 logo_aseco: LogoAsecco.jpg
 logo_limpo: Logolimposervices.jpg
 files_base:
  - ProductoCleaner_1.jpg
  - ProductoCleaner_2.jpg
documental_images: /documental/images/
documental_pdfs: /documental/pdfs/